---
env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - airbnb
globals:
  document: true
  process: true
  window: true
parser: babel-eslint
plugins:
  - flowtype
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    impliedStrict: true
    jsx: true
  ecmaVersion: 8
  sourceType: module
root: true
rules:
  comma-dangle:
    - 2
    - always-multiline
  function-paren-newline:
    - 0
    - multiline
  no-plusplus: 0
  no-restricted-syntax:
    - 0
    - ForOfStatement
  object-curly-newline:
    - 2
    - consistent: true
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  jsx-a11y/no-marquee: 0
  react/jsx-filename-extension: 0
  react/react-in-jsx-scope: 0
  react/jsx-curly-brace-presence: 0
  react/jsx-closing-tag-location: 0
